# Generated by Django 5.1.15 on 2026-06-17 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Full project name (e.g. ERP D365 Implementation — PGE).', max_length=255, verbose_name='Project Name')),
                ('client_name', models.CharField(blank=True, help_text='Name of the client or entity this project belongs to.', max_length=255, verbose_name='Client / Entity')),
                ('description', models.TextField(blank=True, help_text='Short description shown at the top of the public timeline.', verbose_name='Description')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20, verbose_name='Status')),
                ('is_public', models.BooleanField(default=True, help_text='If enabled, anyone with the link can view the project timeline.', verbose_name='Public')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Phase name (e.g. Blueprint Signed, Development, UAT).', max_length=150, verbose_name='Phase Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first.', verbose_name='Order')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'Under Review'), ('REVISED', 'Revised'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Phase description or deliverable notes.', verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End / Target Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Project Phase',
                'verbose_name_plural': 'Project Phases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('guest_name', models.CharField(blank=True, help_text='Display name for unauthenticated visitors.', max_length=100, verbose_name='Guest Name')),
                ('guest_email', models.EmailField(blank=True, help_text='Contact email for unauthenticated visitors (not shown publicly).', max_length=254, verbose_name='Guest Email')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to soft-hide a comment without deleting it.', verbose_name='Visible')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(blank=True, help_text='Set automatically when an authenticated staff user comments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Staff User')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectphase', verbose_name='Phase')),
            ],
            options={
                'verbose_name': 'Project Comment',
                'verbose_name_plural': 'Project Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Short title (e.g. Kick-off Meeting completed).', max_length=200, verbose_name='Update Title')),
                ('content', models.TextField(blank=True, help_text='Full detail or outcome of this update.', verbose_name='Detail')),
                ('attachment', models.FileField(blank=True, help_text='Upload a photo, short video, or small document.', null=True, upload_to='projects/updates/', verbose_name='Attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.projectphase', verbose_name='Phase')),
                ('shared_doc', models.ForeignKey(blank=True, help_text='Optionally link to a Shared Infographic document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to='shared_docs.shareddocument', verbose_name='Linked Document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
