# Generated by Django 5.1.15 on 2026-06-19 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_public_crud',
            field=models.BooleanField(default=False, help_text='If enabled, unauthenticated visitors with the link can add phases and updates.', verbose_name='Public Editable'),
        ),
        migrations.AddField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text='Specific staff users allowed to edit this project.', related_name='followed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Editors / Followers'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='update_date',
            field=models.DateField(blank=True, help_text='Date of this update. Defaults to today if left blank.', null=True, verbose_name='Update Date'),
        ),
        migrations.CreateModel(
            name='PhaseChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task_name', models.CharField(help_text='Description of the task to be completed.', max_length=255, verbose_name='Task Name')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first.', verbose_name='Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='projects.projectphase', verbose_name='Phase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Phase Checklist Item',
                'verbose_name_plural': 'Phase Checklist Items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
