# Generated by Django 5.1.15 on 2026-06-17 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_public_crud',
            field=models.BooleanField(default=False, help_text='If enabled, unauthenticated visitors with the link can add phases and updates.', verbose_name='Public Editable'),
        ),
        migrations.AddField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text='Specific staff users allowed to edit this project.', related_name='followed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Editors / Followers'),
        ),
    ]
