# Generated by Django 5.1.15 on 2026-06-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional banner image for the project timeline header.', null=True, upload_to='projects/covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='phasechecklist',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order — lower numbers appear first (can be negative).', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order — lower numbers appear first (can be negative).', verbose_name='Order'),
        ),
    ]
