version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-rocdesk_db}
      POSTGRES_USER: ${DB_USER:-rocdesk_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Danidan1922#}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-rocdesk_user} -d ${DB_NAME:-rocdesk_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: .
    restart: always
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER:-rocdesk_user}:${DB_PASSWORD:-Danidan1922#}@db:5432/${DB_NAME:-rocdesk_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build: .
    restart: always
    command: celery -A roc_desk worker --loglevel=info
    volumes:
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER:-rocdesk_user}:${DB_PASSWORD:-Danidan1922#}@db:5432/${DB_NAME:-rocdesk_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build: .
    restart: always
    command: celery -A roc_desk beat -l info
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER:-rocdesk_user}:${DB_PASSWORD:-Danidan1922#}@db:5432/${DB_NAME:-rocdesk_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  evolution_api:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: evoapicloud/evolution-api:v2.3.6
    container_name: evolution_api_rocdesk
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://43.134.163.72:8080
      - DOCKER_ENV=true
      - LOG_LEVEL=DEBUG,ERROR,WARN,INFO,LOG,VERBOSE,DARK,WEBHOOKS
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1025062854

      # --- Authentication ---
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=rocdesk-evo-key-2026

      # --- PostgreSQL Configuration ---
      - DATABASE_ENABLED=false
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://openpg:openpgpwd@host.docker.internal:5432/evolution_db?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_rocdesk

      # --- Redis Configuration ---
      - REDIS_ENABLED=true
      - REDIS_URI=redis://redis:6379/6
      - REDIS_PREFIX=evo
      # --- Redis Configuration ---
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/6
      - CACHE_REDIS_PREFIX_KEY=evo

    depends_on:
      - redis

    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  postgres_data:
  redis_data:
  evolution_store:
  media_volume:
  static_volume:
