# Generated by Django 6.0.2 on 2026-02-26 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=520, unique=True, verbose_name='Slug')),
                ('problem_summary', models.TextField(help_text='Concise description of the problem.', verbose_name='Problem Summary')),
                ('root_cause', models.TextField(help_text='Documented root cause of the issue.', verbose_name='Root Cause')),
                ('solution', models.TextField(help_text='Step-by-step resolution procedure.', verbose_name='Solution')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only published articles are visible in the knowledge base.', verbose_name='Published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='cases.casecategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('source_case', models.ForeignKey(blank=True, help_text='The CaseRecord this article was generated from (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cases.caserecord', verbose_name='Source Case')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
