# Generated by Django 6.0.2 on 2026-04-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_article_rejection_reason_article_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('Issue', 'Menangani Masalah'), ('Announcement', 'Pengumuman')], default='Issue', max_length=20, verbose_name='Article Type'),
        ),
    ]
