# Generated by Django 6.0.2 on 2026-04-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('Issue', 'Issue Handling'), ('Announcement', 'Announcement')], default='Issue', max_length=20, verbose_name='Article Type'),
        ),
    ]
