# Generated by Django 6.0.2 on 2026-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_alter_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='problem_summary',
            field=models.TextField(blank=True, help_text='Concise description of the problem.', verbose_name='Problem Summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='root_cause',
            field=models.TextField(blank=True, help_text='Documented root cause of the issue.', verbose_name='Root Cause'),
        ),
        migrations.AlterField(
            model_name='article',
            name='solution',
            field=models.TextField(blank=True, help_text='Step-by-step resolution procedure.', verbose_name='Solution'),
        ),
    ]
