# Generated by Django 6.0.2 on 2026-02-27 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='E.164 format, e.g. +6281234567890', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format (e.g. +6281234567890).', regex='^\\+?[1-9]\\d{6,14}$')], verbose_name='Phone Number'),
        ),
    ]
