# Generated by Django 6.0.2 on 2026-02-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_email_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, help_text="User initials used as a signature (e.g., 'mrs').", max_length=5, verbose_name='Initials'),
        ),
    ]
