# Generated by Django 6.0.2 on 2026-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='initials',
            field=models.CharField(help_text="User initials used as a signature (e.g., 'mrs').", max_length=5, verbose_name='Initials'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(help_text='Nomor Induk Karyawan — unique employee identifier.', max_length=50, null=True, unique=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Human-readable display name (not used for login).', max_length=150, verbose_name='Display Name'),
        ),
    ]
