# Generated by Django 6.0.2 on 2026-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a square ".ico" or ".png" image for the browser tab icon.', null=True, upload_to='site_config/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload the main logo displayed in the navigation bar.', null=True, upload_to='site_config/', verbose_name='Site Logo'),
        ),
    ]
