# Generated by Django 6.0.2 on 2026-02-28 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfig_favicon_siteconfig_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255, verbose_name='IMAP Host')),
                ('imap_port', models.IntegerField(default=993, verbose_name='IMAP Port')),
                ('imap_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='IMAP User')),
                ('imap_password', models.CharField(blank=True, help_text='e.g. Gmail App Password (16 chars, no spaces)', max_length=255, null=True, verbose_name='IMAP App Password')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='SMTP User')),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='SMTP App Password')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('default_from_email', models.CharField(blank=True, help_text='Usually matches SMTP User', max_length=255, null=True, verbose_name='Default From Email')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
