# Generated by Django 6.0.2 on 2026-02-28 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Form Title')),
                ('description', models.TextField(blank=True, verbose_name='Form Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('requires_login', models.BooleanField(default=False, verbose_name='Requires Login to Submit')),
                ('background_color', models.CharField(blank=True, default='#f8fafc', help_text='e.g. #f8fafc or a Tailwind class', max_length=50, verbose_name='Background Color')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='form_backgrounds/', verbose_name='Background Image')),
                ('success_message', models.TextField(default='Thank you! Your response has been submitted.', verbose_name='Success Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Dynamic Form',
                'verbose_name_plural': 'Dynamic Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email Address'), ('dropdown', 'Dropdown Select'), ('radio', 'Multiple Choice (Single Answer)'), ('checkbox', 'Checkboxes (Multiple Answers)'), ('date', 'Date Picker')], default='text', max_length=20)),
                ('label', models.CharField(max_length=255, verbose_name='Field Label/Question')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Help Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='Choices (for Dropdowns/Radios)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.dynamicform')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.dynamicform')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
