# Generated by Django 6.0.2 on 2026-02-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dynamicform_formfield_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='max_upload_size_mb',
            field=models.PositiveIntegerField(default=10, help_text='Maximum allowed file size for form attachments in Megabytes.', verbose_name='Max Upload Size (MB)'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email Address'), ('dropdown', 'Dropdown Select'), ('radio', 'Multiple Choice (Single Answer)'), ('checkbox', 'Checkboxes (Multiple Answers)'), ('date', 'Date Picker'), ('datetime', 'Date & Time Picker'), ('survey', 'Survey Scale (Linear)'), ('attachment', 'File Upload (Single)'), ('attachment_multiple', 'File Upload (Multiple)')], default='text', max_length=20),
        ),
    ]
