# Generated by Django 6.0.2 on 2026-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfig_max_upload_size_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='show_on_portal',
            field=models.BooleanField(default=False, help_text='Display this form as a card on the Client Portal dashboard.', verbose_name='Show on Client Portal'),
        ),
    ]
