# Generated by Django 6.0.2 on 2026-02-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dynamicform_show_on_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='form_headers/', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email Address'), ('dropdown', 'Dropdown Select'), ('radio', 'Multiple Choice (Single Answer)'), ('checkbox', 'Checkboxes (Multiple Answers)'), ('date', 'Date Picker'), ('datetime', 'Date & Time Picker'), ('survey', 'Survey Scale (Linear)'), ('attachment', 'File Upload (Single)'), ('attachment_multiple', 'File Upload (Multiple)'), ('title_desc', 'Title & Description'), ('page_break', 'Section / Page Break')], default='text', max_length=20),
        ),
    ]
