# Generated by Django 6.0.2 on 2026-03-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dynamicform_header_image_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('email', 'Email Address'), ('dropdown', 'Dropdown Select'), ('radio', 'Multiple Choice (Single Answer)'), ('checkbox', 'Checkboxes (Multiple Answers)'), ('date', 'Date Picker'), ('datetime', 'Date & Time Picker'), ('survey', 'Survey Scale (Linear)'), ('attachment', 'File Upload (Single)'), ('attachment_multiple', 'File Upload (Multiple)'), ('title_desc', 'Title & Description'), ('page_break', 'Section / Page Break')], default='text', max_length=20),
        ),
    ]
