# Generated by Django 5.1.15 on 2026-03-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_handle_confidential',
            field=models.BooleanField(default=False, help_text='Allow this user to access tickets in confidential categories.', verbose_name='Can Handle Confidential'),
        ),
    ]
