# Generated by Django 5.1.15 on 2026-03-27 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_can_handle_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='terms_and_privacy',
            field=models.TextField(blank=True, default='Terms of Use\n=============\n\nBy using this Support Desk system, you agree to the following terms:\n\n1. This system is provided for internal use only. All submitted tickets and data are treated as company property.\n2. Users must provide accurate information when submitting tickets or requests.\n3. Misuse of the system, including submitting spam or false reports, may result in restricted access.\n4. The system administrator reserves the right to modify these terms at any time.\n\nPrivacy Policy\n===============\n\n1. Personal data collected (name, email, phone number, employee ID) is used solely for ticket management and communication purposes.\n2. Ticket data may be accessed by authorized support staff and management for resolution and reporting.\n3. Confidential tickets are restricted to authorized personnel only.\n4. We do not share your personal data with third parties without your consent.\n5. Data retention follows company policy. Closed tickets are retained for audit and reporting purposes.', help_text='Terms of use and privacy policy text displayed on the Help & About page.', verbose_name='Terms & Privacy Policy'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('feedback_type', models.CharField(choices=[('Bug', 'Bug Report'), ('Feature', 'Feature Request'), ('Improvement', 'Improvement Suggestion'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
