# Generated by Django 6.0.2 on 2026-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteconfig_terms_and_privacy_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='require_public_login',
            field=models.BooleanField(default=False, help_text='If enabled, all users must be logged in to access the public Ticket Portal and Knowledge Base.', verbose_name='Require Public Login'),
        ),
    ]
