# Generated by Django 6.0.2 on 2026-04-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_siteconfig_require_public_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_access',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Manager', 'Manager'), ('SupportDesk', 'Support Desk'), ('Auditor', 'Auditor'), ('PortalUser', 'Portal User')], default='SupportDesk', max_length=20, verbose_name='Role Access'),
        ),
    ]
