# Generated by Django 5.1.15 on 2026-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_role_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_info',
            field=models.TextField(blank=True, default='', help_text='Contact details (narahubung) shown on the login page footer. Supports plain text or simple HTML.', verbose_name='Contact Info (Narahubung)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='login_image',
            field=models.ImageField(blank=True, help_text='Large background/hero image displayed on the left panel of Theme 2 login. Recommended: portrait or square, min 800×1000px.', null=True, upload_to='site_config/', verbose_name='Login Page Image (Theme 2)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='login_theme',
            field=models.CharField(choices=[('theme1', 'Tema 1 — Classic (Purple Split Panel)'), ('theme2', 'Tema 2 — Modern (Full Image Left, Dark Form Right)')], default='theme1', help_text='Select the visual theme for the login page and related auth screens.', max_length=20, verbose_name='Login Page Theme'),
        ),
    ]
