# Generated by Django 5.1.15 on 2026-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_siteconfig_login_theme_image_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='login_image_2',
            field=models.ImageField(blank=True, help_text='Slide 2 (optional).', null=True, upload_to='site_config/', verbose_name='Login Image 2'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='login_image_3',
            field=models.ImageField(blank=True, help_text='Slide 3 (optional).', null=True, upload_to='site_config/', verbose_name='Login Image 3'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='login_image_4',
            field=models.ImageField(blank=True, help_text='Slide 4 (optional).', null=True, upload_to='site_config/', verbose_name='Login Image 4'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='login_image_5',
            field=models.ImageField(blank=True, help_text='Slide 5 (optional).', null=True, upload_to='site_config/', verbose_name='Login Image 5'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='login_image',
            field=models.ImageField(blank=True, help_text='Slide 1 — hero image for Theme 2 login left panel. Recommended min 800×1000px.', null=True, upload_to='site_config/', verbose_name='Login Image 1'),
        ),
    ]
