# Generated by Django 5.1.15 on 2026-04-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_login_images_2_to_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='login_image_2',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='login_image_3',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='login_image_4',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='login_image_5',
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='login_image',
            field=models.ImageField(blank=True, help_text="Primary hero image for Theme 2 left panel. Add more slides via 'Login Slide Images' below.", null=True, upload_to='site_config/', verbose_name='Login Page Image (Theme 2)'),
        ),
        migrations.CreateModel(
            name='LoginSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended portrait/square, min 800×1000px.', upload_to='site_config/slides/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order')),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_images', to='core.siteconfig', verbose_name='Site Config')),
            ],
            options={
                'verbose_name': 'Login Slide Image',
                'verbose_name_plural': 'Login Slide Images',
                'ordering': ['order'],
            },
        ),
    ]
