# Generated by Django 6.0.2 on 2026-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_login_slide_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Field Settings'),
        ),
    ]
