# Generated by Django 6.0.2 on 2026-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_formfield_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='collect_company',
            field=models.BooleanField(default=False, verbose_name='Collect Company Unit'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='collect_user',
            field=models.BooleanField(default=False, verbose_name='Collect User Login'),
        ),
    ]
