# Generated by Django 6.0.2 on 2026-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_dynamicform_collect_company_dynamicform_collect_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text="User's phone/mobile number.", max_length=30, verbose_name='Phone Number'),
        ),
    ]
