# Generated by Django 5.1.15 on 2026-04-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_encrypt_user_phone_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_29a2bf_idx',
            old_name='core_auditl_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_41600a_idx',
            old_name='core_auditl_actor_idx',
        ),
    ]
