# Generated by Django 5.1.15 on 2026-05-08 15:58

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_alter_caserecord_source_alter_message_channel'),
        ('core', '0031_add_ssoconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyunit',
            options={'ordering': ['code'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AddField(
            model_name='companyunit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a top-level unit. Select a parent to nest this unit under it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.companyunit', verbose_name='Parent Unit'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='google_allowed_domains',
            field=models.CharField(blank=True, help_text='Comma-separated list of allowed email domains for Google SSO (e.g. company.com,subsidiary.co.id). Leave blank to allow any Google account.', max_length=500, verbose_name='Google Allowed Domains'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='google_client_id',
            field=models.CharField(blank=True, help_text='Client ID from Google Cloud Console OAuth 2.0 credentials.', max_length=200, verbose_name='Google Client ID'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='google_client_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Client secret from Google Cloud Console (stored encrypted).', verbose_name='Google Client Secret'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='microsoft_client_id',
            field=models.CharField(blank=True, help_text='Application (client) ID from Azure AD App Registration.', max_length=200, verbose_name='Microsoft Client ID (App ID)'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='microsoft_client_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Client secret from Azure AD App Registration (stored encrypted).', verbose_name='Microsoft Client Secret'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='microsoft_tenant_id',
            field=models.CharField(blank=True, default='organizations', help_text="'organizations' = any Microsoft work/school account. Enter a specific Tenant UUID to restrict login to a single organisation. 'common' = any Microsoft account including personal.", max_length=200, verbose_name='Microsoft Tenant ID'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='sso_enabled',
            field=models.BooleanField(default=False, help_text='Master switch — show SSO login buttons on the login page.', verbose_name='Enable SSO'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='sso_whitelist_category',
            field=models.ForeignKey(blank=True, help_text="Ticket category used for new SSO user whitelist requests. If left blank, the system will automatically use or create an 'SSO Access Request' category.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casecategory', verbose_name='SSO Whitelist Ticket Category'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
