# Generated by Django 5.1.15 on 2026-05-19 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_siteconfig_wa_rate_and_pacing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='ai_max_context_docs',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of relevant articles/pages to include in each AI query. Higher = more context but slower response.', verbose_name='Max Context Documents'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='ai_model_name',
            field=models.CharField(choices=[('gemini-3-flash', 'Gemini 3 Flash (Newest)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash (Recommended)'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (Cheapest)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (Deprecated)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Deprecated)')], default='gemini-2.0-flash', help_text='The Gemini model to use for generating answers.', max_length=100, verbose_name='Gemini Model'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='ai_placeholder_text',
            field=models.CharField(default='Ask something...', help_text='Placeholder text inside the AI question input box.', max_length=200, verbose_name='Input Placeholder'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='ai_rate_limit_per_hour',
            field=models.PositiveIntegerField(default=30, help_text='Maximum questions a single IP/session can ask per hour. Set to 0 to disable rate limiting.', verbose_name='Rate Limit (per hour)'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='ai_system_prompt',
            field=models.TextField(default="You are the AI Assistant for {site_name}.\nYour task: answer user questions ONLY based on the provided context documents.\n\nIMPORTANT Rules:\n1. Answer in the same language as the user's question.\n2. If the answer is NOT in the context, honestly say: 'I'm sorry, but I couldn't find that information in our documentation. Please contact the Support Desk for further assistance.'\n3. DO NOT invent or hallucinate information not present in the context.\n4. Provide concise, clear, and easy-to-understand answers.\n5. If relevant, cite the document from which the information was derived.\n", help_text='Instructions sent to the AI before each question. Use {site_name} as a placeholder for the site name.', verbose_name='System Prompt'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='ai_welcome_message',
            field=models.TextField(default='Hello! I am an AI Assistant ready to help you. Ask me anything about our Knowledge Base and User Manual.', help_text='Message shown at the top of the AI chat panel.', verbose_name='Welcome Message'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_business_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekday numbers (0=Mon … 6=Sun) when broadcasts are allowed. Default: 0,1,2,3,4 (Monday–Friday).', max_length=20, verbose_name='WA Business Days'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_cb_block_hours',
            field=models.PositiveSmallIntegerField(default=4, help_text='Hours all outbound sends stay blocked after the circuit breaker trips. Recommended: 4. Values below 2 provide insufficient recovery time.', verbose_name='WA CB Block Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_cb_max_disconnects',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of disconnects within 24 hours before the circuit breaker trips. Recommended: 2. Higher values are too lenient and allow continued sends during instability.', verbose_name='WA CB Max Disconnects'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_opt_in_ttl_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days a contact is considered opted-in after their last inbound message. Internal broadcast is skipped for contacts outside this window. Recommended: 7. Below 3 is too restrictive; above 30 risks messaging stale contacts.', verbose_name='WA Opt-in TTL (days)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_rate_burst_max',
            field=models.PositiveSmallIntegerField(default=8, help_text='Maximum outbound messages in any rolling 60-second window. Recommended: 8. Values above 12 are risky.', verbose_name='WA Burst Limit (per 60s)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_rate_hour_max',
            field=models.PositiveIntegerField(default=200, help_text='Maximum outbound messages per hour. Recommended: 200. Values above 350 are risky.', verbose_name='WA Per-Hour Limit'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_rate_minute_max',
            field=models.PositiveSmallIntegerField(default=15, help_text='Maximum outbound messages per minute across all recipients. Recommended: 15. Values above 20 are risky.', verbose_name='WA Per-Minute Limit'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_rate_recipient_cooldown',
            field=models.PositiveSmallIntegerField(default=10, help_text='Minimum seconds between two messages to the same phone number. Recommended: 10. Values below 5 risk triggering spam detection.', verbose_name='WA Recipient Cooldown (s)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_read_pause_max_ms',
            field=models.PositiveSmallIntegerField(default=3500, help_text='Maximum milliseconds to pause before starting to type a reply. Recommended: 3500. Values below 1500 look bot-like.', verbose_name='WA Read Pause Max (ms)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_read_pause_min_ms',
            field=models.PositiveSmallIntegerField(default=1000, help_text='Minimum milliseconds to pause before starting to type a reply. Simulates reading the incoming message. Recommended: 1000.', verbose_name='WA Read Pause Min (ms)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='wa_typing_speed_cps',
            field=models.PositiveSmallIntegerField(default=25, help_text='Simulated typing speed in characters per second used to calculate composing duration. Recommended: 25. Values above 40 exceed human typing speed.', verbose_name='WA Typing Speed (chars/s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Karyawan — unique employee identifier.', max_length=50, null=True, unique=True, verbose_name='NIK'),
        ),
    ]
