# Generated by Django 5.1.15 on 2026-06-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_jobrole_siteconfig_job_role_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
