# Generated by Django 5.1.15 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_jobrole_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='marketplace_url',
            field=models.URLField(blank=True, default='http://localhost:5000', help_text='Base URL of the Estalatree licensing server for verification.', verbose_name='Marketplace Server URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_url',
            field=models.URLField(blank=True, default='', help_text='The main public URL of this application (e.g. https://finance.santika.com). Used for generating links in emails and background tasks. Leave blank to fallback to the .env setting.', verbose_name='Base Site URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='wa_inbound_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, incoming WhatsApp messages will create new tickets or append to active sessions.', verbose_name='Enable Inbound (Create Ticket)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='wa_outbound_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, staff can send replies via WhatsApp and system can send outbound notifications.', verbose_name='Enable Outbound (Reply/Escalate)'),
        ),
    ]
