# Generated by Django 5.1.15 on 2026-06-17 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Document title (e.g. D365 Architecture Overview)', max_length=255, verbose_name='Title')),
                ('editor_mode', models.CharField(choices=[('RICH_TEXT', 'Rich Text (Quill)'), ('RAW_HTML', 'Raw HTML/CSS Code')], default='RICH_TEXT', help_text='Choose Raw HTML to embed a complete custom HTML/CSS document.', max_length=20, verbose_name='Editor Mode')),
                ('content', models.TextField(help_text='HTML or Markdown content — will be sanitized before display.', verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, help_text='Disable to revoke public access without deleting the document.', verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Shared Document',
                'verbose_name_plural': 'Shared Documents',
                'db_table': 'projects_shareddocument',
                'ordering': ['-created_at'],
            },
        ),
    ]
