# Generated by Django 6.0.2 on 2026-02-26 04:17

import cases.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text="CSS icon class or emoji, e.g. 'fas fa-laptop-code' or '🖥️'.", max_length=100, verbose_name='Icon')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('PendingInfo', 'Pending Info'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('EvolutionAPI_WA', 'WhatsApp (Evolution API)'), ('Email', 'Email'), ('WebForm', 'Web Form')], default='WebForm', max_length=20, verbose_name='Source')),
                ('problem_description', models.TextField(verbose_name='Problem Description')),
                ('root_cause_analysis', models.TextField(blank=True, help_text='To be filled by support staff during investigation.', verbose_name='Root Cause Analysis')),
                ('solving_steps', models.TextField(blank=True, help_text='Must be completed before marking the case as Resolved.', verbose_name='Solving Steps')),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Stores category-specific form inputs as JSON.', verbose_name='Dynamic Form Data')),
                ('response_due_at', models.DateTimeField(blank=True, help_text='Deadline for first staff response.', null=True, verbose_name='Response Due At')),
                ('resolution_due_at', models.DateTimeField(blank=True, help_text='Deadline for case resolution.', null=True, verbose_name='Resolution Due At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casecategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.employee', verbose_name='Requester')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Ticket Record',
                'verbose_name_plural': 'Ticket Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('body', models.TextField(verbose_name='Message Body')),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], default='IN', max_length=3, verbose_name='Direction')),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Web', 'Web')], default='Web', max_length=20, verbose_name='Channel')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Evolution API message ID or Email Message-ID. Used for dedup.', max_length=255, verbose_name='External ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.caserecord', verbose_name='Case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('sender_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.employee', verbose_name='Sender (Employee)')),
                ('sender_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender (Staff)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file', models.FileField(upload_to=cases.models.attachment_upload_path, verbose_name='File')),
                ('original_filename', models.CharField(blank=True, max_length=500, verbose_name='Original Filename')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
