# Generated by Django 6.0.2 on 2026-02-26 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='link',
            field=models.URLField(blank=True, help_text='URL/link related to this case (e.g. error page, document).', max_length=500, verbose_name='Reference Link'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='requester_email',
            field=models.EmailField(blank=True, help_text='Email provided by the requester on the web form.', max_length=254, verbose_name='Requester Email'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='requester_job_role',
            field=models.CharField(blank=True, max_length=150, verbose_name='Requester Job Role'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Requester Name'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='requester_unit_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Requester Company Unit'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='Linked Employee record (auto-matched if email exists).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.employee', verbose_name='Requester (Employee)'),
        ),
    ]
