# Generated by Django 6.0.2 on 2026-02-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caserecord_link_caserecord_requester_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_error',
            field=models.TextField(blank=True, verbose_name='Delivery Error'),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=20, verbose_name='Delivery Status'),
        ),
    ]
