# Generated by Django 6.0.2 on 2026-02-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_message_delivery_error_message_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='has_unread_messages',
            field=models.BooleanField(default=False, help_text="True if there are new inbound messages that staff hasn't seen.", verbose_name='Has Unread Messages'),
        ),
    ]
