# Generated by Django 6.0.2 on 2026-02-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_caserecord_has_unread_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates if the staff has seen this incoming message.', verbose_name='Is Read'),
        ),
    ]
