# Generated by Django 6.0.2 on 2026-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='root_cause_analysis',
            field=models.CharField(blank=True, help_text='To be filled by support staff during investigation.', max_length=1500, verbose_name='Root Cause Analysis'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='solving_steps',
            field=models.CharField(blank=True, help_text='Must be completed before marking the case as Resolved.', max_length=1500, verbose_name='Solving Steps'),
        ),
    ]
