# Generated by Django 6.0.2 on 2026-02-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_casecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casecomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Internal Comment', 'verbose_name_plural': 'Internal Comments'},
        ),
    ]
