# Generated by Django 6.0.2 on 2026-02-27 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_casecomment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='case_type',
            field=models.CharField(choices=[('Question', 'Question'), ('Incident', 'Incident'), ('Request', 'Request')], default='Incident', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_cases', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='quick_notes',
            field=models.TextField(blank=True, help_text='Internal notes or summary for staff.', verbose_name='Quick Notes'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. login, bug, network)', max_length=255, verbose_name='Tags'),
        ),
    ]
