# Generated by Django 6.0.2 on 2026-02-27 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_caserecord_case_type_caserecord_followers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action', models.CharField(choices=[('Created', 'Case Created'), ('Updated', 'Property Updated'), ('Status Change', 'Status Changed'), ('Assigned', 'Assigned'), ('Reassigned', 'Reassigned'), ('SLA Change', 'SLA Changed'), ('Comment', 'Internal Comment Added')], default='Updated', max_length=50, verbose_name='Action Type')),
                ('field_name', models.CharField(blank=True, help_text='The model field that was changed.', max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cases.caserecord', verbose_name='Case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Case Audit Log',
                'verbose_name_plural': 'Case Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
