# Generated by Django 6.0.2 on 2026-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_casecomment_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cc_emails',
            field=models.CharField(blank=True, help_text='Comma-separated secondary recipients for email channels.', max_length=500, verbose_name='CC Emails'),
        ),
    ]
