# Generated by Django 6.0.2 on 2026-03-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_message_cc_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived tickets are hidden from the main inbox view.', verbose_name='Is Archived'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Tickets marked as spam.', verbose_name='Is Spam'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='master_ticket',
            field=models.ForeignKey(blank=True, help_text='If merged, this links to the primary ticket. Sub-tickets are hidden from the main list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tickets', to='cases.caserecord', verbose_name='Master Ticket'),
        ),
    ]
