# Generated by Django 6.0.2 on 2026-03-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_caserecord_is_archived_caserecord_is_spam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='template_text',
            field=models.TextField(blank=True, help_text='Optional text template for the problem description field.', verbose_name='Template Text'),
        ),
    ]
