# Generated by Django 6.0.2 on 2026-03-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_casecategory_template_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='template_subject',
            field=models.CharField(blank=True, help_text='Optional text template for the subject field.', max_length=500, verbose_name='Template Subject'),
        ),
    ]
