# Generated by Django 6.0.2 on 2026-03-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_casecategory_template_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when staff last opened this ticket's detail page.", null=True, verbose_name='Last Viewed At'),
        ),
        migrations.AlterField(
            model_name='caseauditlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cases.caserecord', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_comments', to='cases.caserecord', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='message',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.caserecord', verbose_name='Ticket'),
        ),
    ]
