# Generated by Django 6.0.2 on 2026-03-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_add_last_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='prefix_code',
            field=models.CharField(default='RQ', help_text='2-letter or number prefix for ticket sequence (e.g. RQ, IN, HR).', max_length=2, verbose_name='Prefix Code'),
        ),
    ]
