# Generated by Django 6.0.2 on 2026-03-11 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_casecategory_prefix_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='edit_permission_status',
            field=models.CharField(choices=[('None', 'None'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', help_text='Tracks approval workflow for editing closed tickets.', max_length=20, verbose_name='Edit Permission Status'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='edit_request_reason',
            field=models.TextField(blank=True, verbose_name='Edit Request Reason'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='edit_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Edit Requested By'),
        ),
    ]
