# Generated by Django 6.0.2 on 2026-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_caserecord_edit_permission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='amendment_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks how many times a closed ticket was edited.', verbose_name='Amendment Count'),
        ),
    ]
