# Generated by Django 6.0.2 on 2026-03-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_caserecord_amendment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='hold_wa_session',
            field=models.BooleanField(default=False, help_text='If true, bypasses the 30-minute auto end-session for WhatsApp conversations.', verbose_name='Hold WA Session'),
        ),
    ]
