# Generated by Django 5.1.15 on 2026-03-25 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_message_is_deleted_message_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a Main Category. Select a parent to make this a Sub-Category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cases.casecategory', verbose_name='Parent Category'),
        ),
    ]
