# Generated by Django 5.1.15 on 2026-03-26 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_add_parent_to_casecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCATemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text="Short label shown on the quick-fill button, e.g. 'Penambahan Akses User'.", max_length=200, verbose_name='Template Name')),
                ('rca_text', models.TextField(blank=True, help_text='Template text for the RCA field. Leave blank to skip.', verbose_name='Root Cause Analysis Text')),
                ('solving_steps_text', models.TextField(blank=True, help_text='Template text for the Solving Steps field. Leave blank to skip.', verbose_name='Solving Steps Text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display Order')),
                ('category', models.ForeignKey(blank=True, help_text='Leave empty to make this template available for all categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rca_templates', to='cases.casecategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'RCA Template',
                'verbose_name_plural': 'RCA Templates',
                'ordering': ['order', 'name'],
            },
        ),
    ]
