# Generated by Django 5.1.15 on 2026-03-26 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_add_rca_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='confidential_access',
            field=models.ManyToManyField(blank=True, help_text='Users who are allowed to access this confidential ticket.', related_name='confidential_cases', to=settings.AUTH_USER_MODEL, verbose_name='Confidential Access'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Confidential tickets are only accessible by whitelisted users.', verbose_name='Confidential'),
        ),
    ]
