# Generated by Django 5.1.15 on 2026-03-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_add_confidential_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caserecord',
            name='confidential_access',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='is_confidential',
        ),
        migrations.AddField(
            model_name='casecategory',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text="Tickets in this category are confidential — only users with 'can handle confidential' permission can access them.", verbose_name='Confidential Category'),
        ),
    ]
