# Generated by Django 5.1.15 on 2026-03-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_remove_caserecord_confidential_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='quoted_message',
            field=models.ForeignKey(blank=True, help_text='The message being replied to (quote reply).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='cases.message', verbose_name='Quoted Message'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='hold_wa_session',
            field=models.BooleanField(default=False, help_text='If true, bypasses the 60-minute auto end-session for WhatsApp conversations.', verbose_name='Hold WA Session'),
        ),
    ]
