# Generated by Django 6.0.2 on 2026-04-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_add_quoted_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='is_attachment_mandatory',
            field=models.BooleanField(default=False, help_text='If checked, users must upload at least one attachment when submitting a ticket in this category.', verbose_name='Attachment Mandatory'),
        ),
    ]
