# Generated by Django 5.1.15 on 2026-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_chat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='source',
            field=models.CharField(choices=[('EvolutionAPI_WA', 'WhatsApp (Evolution API)'), ('Email', 'Email'), ('WebForm', 'Web Form'), ('Teams_Bot', 'Microsoft Teams (Bot)')], default='WebForm', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Web', 'Web'), ('Teams', 'Microsoft Teams')], default='Web', max_length=20, verbose_name='Channel'),
        ),
    ]
