# Generated by Django 5.1.15 on 2026-06-24 16:27

import cases.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_alter_caserecord_status_and_more'),
        ('esign', '0009_remove_signaturedocument_certificate_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='form_stages',
            field=models.JSONField(blank=True, default=list, help_text='List of stages (e.g. ["Initiator", "Vendor", "IT Ops"]). The first stage is automatically assigned to the form creator.', verbose_name='Form Stages'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='is_standalone',
            field=models.BooleanField(default=False, help_text='If true, this form can be submitted independently from the e-Forms portal, without needing a Support Ticket.', verbose_name='Standalone Form'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='document_templates/logos/', verbose_name='Document Logo'),
        ),
        migrations.AddField(
            model_name='documenttemplatefield',
            name='assigned_stage',
            field=models.CharField(blank=True, help_text="Which stage fills this field? (e.g. 'Vendor'). Leave blank for all stages.", max_length=100, verbose_name='Assigned Stage'),
        ),
        migrations.AddField(
            model_name='documenttemplatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('richtext', 'Rich Text (HTML)'), ('date', 'Date'), ('repeater', 'Table / Repeater')], default='richtext', max_length=20, verbose_name='Field Type'),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('data_payload', models.JSONField(blank=True, default=dict, verbose_name='Form Data Payload')),
                ('current_stage', models.CharField(blank=True, max_length=100, verbose_name='Current Stage')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('pending_esign', 'Pending E-Sign'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('guest_token', models.CharField(blank=True, db_index=True, help_text='Allows public/vendor access to fill their assigned stage.', max_length=64, verbose_name='Guest Token')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to=cases.models.eform_pdf_path, verbose_name='Generated PDF')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_forms', to=settings.AUTH_USER_MODEL, verbose_name='Initiator')),
                ('signature_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_form', to='esign.signaturedocument', verbose_name='E-Sign Document')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to='cases.documenttemplate', verbose_name='Template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
