# Generated by Django 5.1.15 on 2026-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_documenttemplate_form_stages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplatefield',
            name='esign_role',
            field=models.CharField(blank=True, choices=[('', '-- No E-Sign Mapping --'), ('signer_1_name', '[E-Sign] Signer 1 - Name'), ('signer_1_email', '[E-Sign] Signer 1 - Email'), ('signer_2_name', '[E-Sign] Signer 2 - Name'), ('signer_2_email', '[E-Sign] Signer 2 - Email'), ('signer_3_name', '[E-Sign] Signer 3 - Name'), ('signer_3_email', '[E-Sign] Signer 3 - Email')], default='', max_length=50, verbose_name='E-Sign Role Mapping'),
        ),
        migrations.AddField(
            model_name='documenttemplatefield',
            name='variable_name',
            field=models.CharField(blank=True, help_text="Unique identifier (e.g. 'vendor_name'). Used for PDF placeholders {{ vendor_name }} and E-Sign mapping.", max_length=100, verbose_name='Variable Name'),
        ),
    ]
