# Generated by Django 5.1.15 on 2026-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_documenttemplatefield_esign_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='esign_role',
            field=models.CharField(blank=True, choices=[('', '-- No E-Sign Mapping --'), ('signer_1_name', '[E-Sign] Signer 1 - Name'), ('signer_1_email', '[E-Sign] Signer 1 - Email'), ('signer_2_name', '[E-Sign] Signer 2 - Name'), ('signer_2_email', '[E-Sign] Signer 2 - Email'), ('signer_3_name', '[E-Sign] Signer 3 - Name'), ('signer_3_email', '[E-Sign] Signer 3 - Email'), ('signer_4_name', '[E-Sign] Signer 4 - Name'), ('signer_4_email', '[E-Sign] Signer 4 - Email'), ('signer_5_name', '[E-Sign] Signer 5 - Name'), ('signer_5_email', '[E-Sign] Signer 5 - Email'), ('signer_6_name', '[E-Sign] Signer 6 - Name'), ('signer_6_email', '[E-Sign] Signer 6 - Email'), ('signer_7_name', '[E-Sign] Signer 7 - Name'), ('signer_7_email', '[E-Sign] Signer 7 - Email'), ('signer_8_name', '[E-Sign] Signer 8 - Name'), ('signer_8_email', '[E-Sign] Signer 8 - Email'), ('signer_9_name', '[E-Sign] Signer 9 - Name'), ('signer_9_email', '[E-Sign] Signer 9 - Email'), ('signer_10_name', '[E-Sign] Signer 10 - Name'), ('signer_10_email', '[E-Sign] Signer 10 - Email')], default='', max_length=50, verbose_name='E-Sign Role Mapping'),
        ),
    ]
