# Generated by Django 5.1.15 on 2026-06-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0041_alter_documenttemplatefield_esign_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplatefield',
            name='esign_role',
        ),
        migrations.AddField(
            model_name='documenttemplatefield',
            name='is_signer',
            field=models.BooleanField(default=False, help_text='Check this if the input of this field should be treated as a unique Signer (Name or Email) for the E-Sign process.', verbose_name='Is E-Signer?'),
        ),
    ]
