# Generated by Django 5.1.15 on 2026-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0043_casecategory_default_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='requester_phone',
            field=models.CharField(blank=True, help_text='Phone number (E.164) provided by the requester on the web form.', max_length=20, verbose_name='Requester Phone'),
        ),
    ]
