# Generated by Django 5.1.15 on 2026-04-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('webhook_received', 'Webhook Received'), ('activated', 'License Activated'), ('expired', 'License Expired'), ('suspended', 'License Suspended'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('verification_ok', 'Online Verification Succeeded'), ('verification_failed', 'Online Verification Failed'), ('fraud_attempt', 'Fraud Attempt Detected'), ('disconnected_wa', 'WhatsApp Disconnected (License)'), ('disconnected_email', 'Email Disconnected (License)')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(help_text='Result of HMAC signature validation (if applicable).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Audit Log',
                'verbose_name_plural': 'License Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, help_text='Django-signed encoded key — NOT plain text.', max_length=500)),
                ('issued_to', models.CharField(blank=True, help_text='Company name or email.', max_length=255)),
                ('plan_tier', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='trial', max_length=30)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace Period'), ('partial_lock', 'Partial Lock'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('unlicensed', 'Unlicensed')], default='trial', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = perpetual license.', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last successful online verification timestamp.', null=True)),
                ('max_agents', models.PositiveIntegerField(default=3)),
                ('features_json', models.JSONField(default=dict, help_text='Feature flags for this installation. Example: {"whatsapp": true, "email_settings": true}')),
                ('install_fingerprint', models.CharField(blank=True, help_text='SHA-256(domain + SECRET_KEY[:12] + product_id) — binds license to this server.', max_length=64)),
                ('marketplace_endpoint', models.URLField(blank=True, help_text='Marketplace base URL used for re-verification.')),
            ],
            options={
                'verbose_name': 'License Record',
                'verbose_name_plural': 'License Record',
            },
        ),
        migrations.CreateModel(
            name='TrialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_date', models.DateField(unique=True)),
                ('first_access_at', models.DateTimeField(auto_now_add=True)),
                ('total_seconds_used', models.PositiveIntegerField(default=0, help_text='Accumulated seconds used today (max = TRIAL_DURATION_SECONDS).')),
            ],
            options={
                'verbose_name': 'Trial Record',
                'verbose_name_plural': 'Trial Records',
                'ordering': ['-trial_date'],
            },
        ),
    ]
