# Generated by Django 6.0.2 on 2026-04-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseauditlog',
            name='event',
            field=models.CharField(choices=[('webhook_received', 'Webhook Received'), ('activated', 'License Activated'), ('deactivated', 'License Deactivated'), ('expired', 'License Expired'), ('suspended', 'License Suspended'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('verification_ok', 'Online Verification Succeeded'), ('verification_failed', 'Online Verification Failed'), ('fraud_attempt', 'Fraud Attempt Detected'), ('disconnected_wa', 'WhatsApp Disconnected (License)'), ('disconnected_email', 'Email Disconnected (License)')], max_length=32),
        ),
    ]
