# Generated by Django 5.1.15 on 2026-04-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_add_deactivated_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserecord',
            name='install_fingerprint',
            field=models.CharField(blank=True, help_text='SHA-256(domain + INSTALL_KEY + product_id) — binds license to this server.', max_length=64),
        ),
    ]
