# Generated by Django 5.1.15 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_alter_licenseauditlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserecord',
            name='activation_token',
            field=models.CharField(blank=True, help_text='Remote activation token from Estalatree. If empty, the license has not been validated online.', max_length=255, null=True, verbose_name='Activation Token'),
        ),
    ]
