# Generated by Django 5.1.15 on 2026-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_licenserecord_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserecord',
            name='activation_token',
            field=models.CharField(blank=True, default='', help_text='Activation token issued by Estalatree upon successful activation. Sent back during validation.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='licenserecord',
            name='license_key',
            field=models.CharField(blank=True, default='', help_text='Django-signed encoded key — NOT plain text.', max_length=500),
        ),
    ]
