# Generated by Django 5.1.15 on 2026-06-02 05:38

import django.db.models.deletion
import esign.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureFlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Template Name')),
                ('routing_mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20, verbose_name='Routing Mode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Signing Flow Template',
                'verbose_name_plural': 'Signing Flow Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('original_pdf', models.FileField(upload_to=esign.models._original_pdf_path, verbose_name='Original PDF')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to=esign.models._signed_pdf_path, verbose_name='Signed PDF')),
                ('message', models.TextField(blank=True, help_text='Optional note sent to all signers with the signing request.', verbose_name='Message to Signers')),
                ('routing_mode', models.CharField(choices=[('sequential', 'Sequential (one by one)'), ('parallel', 'Parallel (all at once)')], default='sequential', max_length=20, verbose_name='Routing Mode')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signatures'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('page_count', models.PositiveIntegerField(default=1, verbose_name='Page Count')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('document_hash', models.CharField(blank=True, help_text='SHA-256 hash of the original PDF bytes for tamper-evidence.', max_length=64, verbose_name='Document SHA-256')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Signature Document',
                'verbose_name_plural': 'Signature Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent for Signing'), ('viewed', 'Viewed by Signer'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('reminded', 'Reminder Sent'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled')], db_index=True, max_length=20, verbose_name='Event')),
                ('actor_label', models.CharField(blank=True, help_text='Name/email for external actors not in the system.', max_length=300, verbose_name='Actor Label')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('detail', models.TextField(blank=True, verbose_name='Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esign_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor (User)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='esign.signaturedocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Signature Event',
                'verbose_name_plural': 'Signature Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('external_name', models.CharField(blank=True, help_text='Full name for signers who do not have a system account.', max_length=255, verbose_name='External Name')),
                ('external_email', models.EmailField(blank=True, help_text='Email address for signers who do not have a system account.', max_length=254, verbose_name='External Email')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order in which this signer acts (for sequential routing).', verbose_name='Signing Order')),
                ('role', models.CharField(choices=[('signer', 'Signer'), ('approver', 'Approver')], default='signer', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('waiting', 'Waiting (not yet their turn)'), ('pending', 'Pending (action required)'), ('signed', 'Signed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Rejection reason or optional comment left by the signer.', verbose_name='Notes')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Magic-link token for signer access without login.', unique=True, verbose_name='Access Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Acted At')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=esign.models._signature_image_path, verbose_name='Signature Image')),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Signed From IP')),
                ('signed_user_agent', models.TextField(blank=True, verbose_name='Signed User Agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='esign.signaturedocument', verbose_name='Document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for external signers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esign_signers', to=settings.AUTH_USER_MODEL, verbose_name='System User')),
            ],
            options={
                'verbose_name': 'Signer',
                'verbose_name_plural': 'Signers',
                'ordering': ['document', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SignaturePlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initial', 'Initial'), ('date', 'Date'), ('name', 'Name')], default='signature', max_length=20, verbose_name='Field Type')),
                ('page_number', models.PositiveIntegerField(default=1, help_text='1-based page number on the PDF.', verbose_name='Page Number')),
                ('x', models.FloatField(verbose_name='X (normalized)')),
                ('y', models.FloatField(verbose_name='Y (normalized)')),
                ('width', models.FloatField(verbose_name='Width (normalized)')),
                ('height', models.FloatField(verbose_name='Height (normalized)')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='esign.signaturedocument', verbose_name='Document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='esign.signer', verbose_name='Signer')),
            ],
            options={
                'verbose_name': 'Signature Placement',
                'verbose_name_plural': 'Signature Placements',
                'ordering': ['document', 'page_number', 'signer__order'],
            },
        ),
        migrations.CreateModel(
            name='SignatureFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('role', models.CharField(choices=[('signer', 'Signer'), ('approver', 'Approver')], default='signer', max_length=20, verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_steps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='esign.signatureflowtemplate', verbose_name='Flow Template')),
            ],
            options={
                'verbose_name': 'Flow Step',
                'verbose_name_plural': 'Flow Steps',
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('document', 'user'), name='esign_unique_signer_per_document'),
        ),
    ]
