# Generated by Django 5.1.15 on 2026-06-02 08:16

import django.db.models.deletion
import esign.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDrawSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('signature_data', models.TextField(blank=True, verbose_name='Signature Data (base64)')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Mobile Draw Session',
                'verbose_name_plural': 'Mobile Draw Sessions',
            },
        ),
        migrations.AlterField(
            model_name='signer',
            name='signature_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=esign.models._signature_image_path, verbose_name='Signature Image'),
        ),
        migrations.CreateModel(
            name='UserSavedSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField(verbose_name='Signature Data (base64)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_signature', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved Signature',
                'verbose_name_plural': 'Saved Signatures',
            },
        ),
    ]
