# Generated by Django 5.1.15 on 2026-06-04 02:23

import esign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0008_signer_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaturedocument',
            name='certificate_style',
        ),
        migrations.AddField(
            model_name='signaturedocument',
            name='document_code',
            field=models.CharField(blank=True, default=esign.models.generate_document_code, help_text='Unique sequence/hash identifier for this document.', max_length=20, null=True, verbose_name='Document Code'),
        ),
        migrations.AddField(
            model_name='signer',
            name='stamp_use_logo',
            field=models.BooleanField(default=True, verbose_name='Use Company Logo'),
        ),
    ]
