# Generated by Django 5.1.15 on 2026-06-17 01:36

import esign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0008_signer_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaturedocument',
            name='certificate_style',
        ),
        migrations.AddField(
            model_name='signaturedocument',
            name='document_code',
            field=models.CharField(blank=True, default=esign.models.generate_document_code, help_text='Unique sequence/hash identifier for this document.', max_length=20, null=True, verbose_name='Document Code'),
        ),
        migrations.AddField(
            model_name='signer',
            name='company',
            field=models.CharField(blank=True, help_text='Company or organization of the signer.', max_length=150, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='signer',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title or role of the signer.', max_length=150, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='signer',
            name='stamp_use_logo',
            field=models.BooleanField(default=True, verbose_name='Use Company Logo'),
        ),
        migrations.AlterField(
            model_name='signatureevent',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent for Signing'), ('viewed', 'Viewed by Signer'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('reminded', 'Reminder Sent'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled'), ('amended', 'Amended'), ('reassigned', 'Reassigned'), ('force_completed', 'Force Completed')], db_index=True, max_length=20, verbose_name='Event'),
        ),
    ]
