# Generated by Django 5.1.15 on 2026-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPortalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='App Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(max_length=500, verbose_name='App URL')),
                ('icon_emoji', models.CharField(default='🌐', help_text='Displayed when no image is uploaded.', max_length=10, verbose_name='Icon Emoji')),
                ('icon_image', models.ImageField(blank=True, help_text='If uploaded, takes priority over the emoji icon.', null=True, upload_to='app_portal/icons/', verbose_name='Icon Image')),
                ('badge_text', models.CharField(blank=True, help_text="Optional short label, e.g. 'New', 'Beta', 'Internal'.", max_length=50, verbose_name='Badge')),
                ('accent_color', models.CharField(choices=[('indigo', 'Indigo'), ('slate', 'Slate'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('rose', 'Rose'), ('sky', 'Sky Blue'), ('violet', 'Violet'), ('teal', 'Teal')], default='indigo', help_text='Card header gradient color theme.', max_length=20, verbose_name='Accent Color')),
                ('accessible_roles', models.CharField(default='all', help_text="Select which roles can see this app. Leave as 'all' to show to every logged-in user.", max_length=200, verbose_name='Accessible By')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'App Portal Entry',
                'verbose_name_plural': 'App Portal Entries',
                'ordering': ['order', 'name'],
            },
        ),
    ]
